USE movieDB;
DROP TABLE IF EXISTS USER_MOVIE_RATING_COMMENT;
DROP TABLE IF EXISTS USER_MOVIE_RATING;
DROP TABLE IF EXISTS USER_MOVIE_COMMENT;

CREATE TABLE USER_MOVIE_RATING (

RATING_ID INT(10) NOT NULL	AUTO_INCREMENT,

USER_ID INT(10),

MOVIE_ID INT,

RATING FLOAT(5,2),

PRIMARY KEY (RATING_ID) 

) ;

ALTER TABLE USER_MOVIE_RATING ADD FOREIGN KEY (MOVIE_ID) 

REFERENCES MOVIE (MOVIE_ID) ON DELETE CASCADE;

ALTER TABLE USER_MOVIE_RATING ADD FOREIGN KEY (USER_ID) 

REFERENCES USERS (ID) ON DELETE CASCADE;

CREATE TABLE USER_MOVIE_COMMENT (

COMMENT_ID INT(10) NOT NULL	AUTO_INCREMENT,

USER_ID INT(10),

MOVIE_ID INT,

COMMENT TEXT,

PRIMARY KEY (COMMENT_ID) 

) ;

ALTER TABLE USER_MOVIE_COMMENT ADD FOREIGN KEY (MOVIE_ID) 

REFERENCES MOVIE (MOVIE_ID) ON DELETE CASCADE;

ALTER TABLE USER_MOVIE_COMMENT ADD FOREIGN KEY (USER_ID) 

REFERENCES USERS (ID) ON DELETE CASCADE;